---
title: "Group 14 Data Memo"
author: "Jordi Parry, Albert Kim, Zachary Kornbluth"
date: "4/8/2021"
output: html_document
---

# Data Source
For this project, we will be using the 2019-2020 Major League Baseball Regular Season dataset containing batting statistics for players with at least 100 plate appearances for both years. Specifically, predictors within this dataset vary from measures of physical strength such as sprint speed and arm strength, batting statistics such as plate appearances, on base plus slugging percentages, and player information such as age and name. This data is obtained from the website Baseball Savant, found at https://baseballsavant.mlb.com/. This dataset is what Jordi used for his 301-1 final project in the fall. 

The specific "custom leaderboard" we plan to use to pull this data is found at http://bit.ly/JordiParryProjectDataMLB

# Project Timeline
We plan to load, process, and clean the data within the next week in order to begin the EDA for the dataset. Once the EDA is completed by the specified due date, the rest of the time for the quarter will be used to build models and fine tune hyperparameters with the goal of achieveing the lowest RMSE score possible for our outcome variable.

# Research Question
The main research question for our final project is the following: can a player's on-base plus slugging percentage be predicted given player's batting performance measures? By nature, this research question is predictive and regressive as the model seeks to predict a single percentage given all other predictors. As an advanced statistic, the on-base plus slugging percentage is an important measure that describes a player's overall offensive capabilities in baseball, and therefore, prediction of this percentage may provide insight into a player's skill given collected batting data. Given a high efficacy, this model may be useful for baseball coaches and administration for scouting new talent as well as assessing current players' performances.

As stated above, the response variable is `on_base_plus_slg`, which is the player's on-base percentage plus his slugging percentage, a representation of batting ability. Some variables we expect to be useful in modeling the response are the player's age, average exit velocity, and launch angle, as these measures are often also used as batting ability indicators. 

# Potential Difficulties
Luckily, the data does not have missingness issues and we do not expect to see many issues, as the data is relatively tidy.  However, we will need to remove certain columns from the dataset, such as the expected outcome stats like xwoba and xslg.